### ISSUE TITLE
Move support classes to ensembl-genes repo

### ISSUE THREAD

**Issue by leannehaggerty** [Ensembl/ensembl-genes-api#2]
Support classes can be found here
https://github.com/Ensembl/ensembl-analysis/tree/experimental/gbiab/scripts/genebuild/gbiab/support_classes

- [x] #5
- [x] #6
- [x] #7
- [x] #8
- [x] #9
- [x] #10

**Comment by thibauthourlier** [comment]
List moved in the first comment

**Comment by ndliberial** [comment]
I will work on the selected files above.

**Comment by jamie-m-a** [comment]
I'll pick up the remaining classes (exon, intron, sequence, gtf adapter)

**Comment by thibauthourlier** [comment]
Information about coding guidelines and documentation https://www.ebi.ac.uk/seqdb/confluence/display/ENS/Ensembl+Coding+Guidelines#EnsemblCodingGuidelines-Python

**Comment by ndliberial** [comment]
I have taken the gene and transcript.py classes.

**Comment by williamstark01** [comment]
Let me know if I can help with anything.
